This is an introduction to a Java library named `materialstore` that I (kazurayam) developed.

== Setting up a project

Here I assume you have a seasoned programming skill in Java, and you have installed the build tool link:https://gradle.org/install/[Gradle]. Now let us create a project where you write some Java code for practice.

I created a working directory under my home directory: `~/tmp/sampleProject`.

[source, shell]
----
$ cd ~/tmp/
$ mkdir sampleProject
----

You want to initialize it as a Gradle project, so you would operate in the console as this:

[source, shell]
----
$ cd ~/tmp/sampleProject
$ gradle init

Select type of project to generate:
  1: basic
  2: application
  3: library
  4: Gradle plugin
Enter selection (default: basic) [1..4] 1

Select build script DSL:
  1: Groovy
  2: Kotlin
Enter selection (default: Groovy) [1..2] 1

Generate build using new APIs and behavior (some features may change in the next minor release)? (default

Project name (default: sampleProject):

> Task :init
Get more help with your project: Learn more about Gradle by exploring our samples at https://docs.gradle.org/7.4.2/samples

BUILD SUCCESSFUL in 28s
----

Then you will find a file `sampleProject/settings.gradle` has been created, which looks like:

[source, gradle]
.settings.gradle
----
rootProject.name = 'sampleProject'
----

You will also find a file `sampleProject/build.gradle` file, but it will be empty (comments only). So you want to edit it, like this.

[source, gradle]
.build.gradle
----
include::../../build.gradle[lines=1..30]
----

Please note that in the build.gradle we declared the dependency to the `materialstore` library, which is published at the Maven Central repository.

* https://mvnrepository.com/artifact/com.kazurayam/materialstore

You can check if the project is properly setup by executing a command, as follows:

[source]
----
$ cd ~/tmp/sampleProject/
$ gradle dependencies --configuration testImplementation

> Task :dependencies

------------------------------------------------------------
Root project 'materialstore-tutorial'
------------------------------------------------------------

testImplementation - Implementation only dependencies for source set 'test'. (n)
+--- com.kazurayam:materialstore:0.16.5 (n)
+--- org.freemarker:freemarker:2.3.31 (n)
+--- com.google.guava:guava:31.1-jre (n)
+--- com.google.code.gson:gson:2.8.9 (n)
+--- org.slf4j:slf4j-api:1.7.25 (n)
+--- org.slf4j:slf4j-simple:1.7.25 (n)
\--- org.junit.jupiter:junit-jupiter-api:5.9.2 (n)

(n) - A dependency or dependency configuration that cannot be resolved.

A web-based, searchable dependency report is available by adding the --scan option.

BUILD SUCCESSFUL in 1s
1 actionable task: 1 executed
----
