== Taking screenshots of a website and compile a report as HTML

We will read the code of link:https://github.com/kazurayam/materialstore-tutorial/blob/develop/src/test/java/my/sample/T09SeleniumShootingsTest.java[`my.sample.T09SeleniumShootingsTest`].

The sample code opens some web pages in a browser, take screenshots of the pages, and save the PNG files into the `store` directory associating Metadata with each Material objects. The code uses link:https://www.selenium.dev/documentation/webdriver/[WebDriver] library to automate interactions with web browser and tak screenshots. It persists the images into the "store" directory on disk using the materialstore library. Eventually it compiles an HTML report using the materialstore library.

=== WebDriver

I assume that you have enough knowledge about `WebDriver`. If not, please get introduced by the tutorials on the Internet, for example:

- link:https://www.guru99.com/selenium-tutorial.html[]

=== the sample code

Have a look at the source of link:https://github.com/kazurayam/materialstore-tutorial/blob/develop/src/test/java/my/sample/T09SeleniumShootingsTest.java[`my.sample.T09SeleniumShootingsTest`]

[source]
----
include::../src/test/java/my/sample/T09SeleniumShootingsTest.java[]
----


The `T09SeleniumShootingsTest` class calls some helper classes:

- link:https://github.com/kazurayam/materialstore-tutorial/blob/develop/src/test/java/my/sample/MaterializeUtils.java[`my.sample.MaterializeUtils`]
- link:https://github.com/kazurayam/materialstore-tutorial/blob/develop/src/test/java/my/sample/SharedMethods.java[`my.sample.SharedMethods`]
- link:https://github.com/kazurayam/materialstore-tutorial/blob/develop/src/test/java/my/sample/TestHelper.java[`my.sample.TestHelper`]

The code depends on several external libraries

- link:https://github.com/kazurayam/ashotwrapper[AShotWrapper]
- link:https://github.com/kazurayam/inspectus[inspectus]

By running `my.sample.T9SeleniumShootingTest` I got an HTML report:

- link:



