== 7th example: various JobTimestamp operations

We are going to read the code of

- link:https://github.com/kazurayam/materialstore-tutorial/blob/master/src/test/java/my/sample/T07JobTimestampOperationsTest.java[my.sample.T07JobTimestampOperationsTest]

The `store` directory has a unified format of sub-directories like this:

[source]
----
$ tree -L 4 .
.
└── store
    ├── test05_select_lest_of_materials
    │   └── 20230519_143612
    │       ├── index
    │       └── objects
    ├── test05_select_with_Regex
    │   ├── 20230519_164822
    │   │   ├── index
    │   │   └── objects
    │   └── 20230519_164834
    │       ├── index
    │       └── objects
    └── test05_select_with_RegularExpression
        └── 20230519_150156
            ├── index
            └── objects
----

The tree has a fixed subdirectory structure:

- `store/<JobName>/<JobTimestamp>/index`
- `store/<JobName>/<JobTimestamp>/objects`

This directory structure is convenient to store the web resources (screenshot images, etc) downloaded from the remote services during our automated Web UI tests.

The `<JobName>` directory will be the top level classification of the downloaded resources. Obviously the `<JobName>` directory will represent which set of test scripts created it. And `<JobTimestamp>` directory will represent the timing when we execute the test.

The `com.kazurayam.materialstore.core.JobTimestamp` class implements a rich set of methods to create/modify/inspect instances. Let me cover them with sample codes.

=== Constructing a JobTimestamp that represents the current timestamp

[source]
----
include::../src/test/java/my/sample/T07JobTimestampOperationsTest.java[lines=14..18]
----

=== Constructing a JobTimestamp with String argument

[source]
----
include::../src/test/java/my/sample/T07JobTimestampOperationsTest.java[lines=20..25]
----

=== Constructing a JobTimestamp with LocalDateTime argument

[source]
----
include::../src/test/java/my/sample/T07JobTimestampOperationsTest.java[lines=27..32]
----

=== Getting a LocalDateTime out of a JobTimestamp object

[source]
----
include::../src/test/java/my/sample/T07JobTimestampOperationsTest.java[lines=34..39]
----

=== Verifying if a String is in a valid JobTimestamp format

[source]
----
include::../src/test/java/my/sample/T07JobTimestampOperationsTest.java[lines=41..45]
----

=== Equals method

[source]
----
include::../src/test/java/my/sample/T07JobTimestampOperationsTest.java[lines=47..54]
----

=== CompareTo method

[source]
----
include::../src/test/java/my/sample/T07JobTimestampOperationsTest.java[lines=56..64]
----

=== Finding the maximum value

[source]
----
include::../src/test/java/my/sample/T07JobTimestampOperationsTest.java[lines=66..72]
----

=== plus operations

[source]
----
include::../src/test/java/my/sample/T07JobTimestampOperationsTest.java[lines=74..80]
----

=== minus operations

[source]
----
include::../src/test/java/my/sample/T07JobTimestampOperationsTest.java[lines=82..88]
----

=== Getting the end of the month

[source]
----
include::../src/test/java/my/sample/T07JobTimestampOperationsTest.java[lines=90..95]
----

=== Getting the beginning of the month

[source]
----
include::../src/test/java/my/sample/T07JobTimestampOperationsTest.java[lines=97..102]
----

=== Getting the difference seconds between 2 JobTimestamp objects

[source]
----
include::../src/test/java/my/sample/T07JobTimestampOperationsTest.java[lines=104..110]
----

=== Creating a JobTimestamp later than the given base JobTimestamp

[source]
----
include::../src/test/java/my/sample/T07JobTimestampOperationsTest.java[lines=113..120]
----

=== Compare a JobTimestamp against a base JobTimestamp to find one newer than the base

[source]
----
include::../src/test/java/my/sample/T07JobTimestampOperationsTest.java[lines=122..133]
----





