== 8th example: Store class basics

We will read the code of link:https://github.com/kazurayam/materialstore-tutorial/blob/develop/src/test/java/my/sample/T08StoreBasics.java[my.sample.T08StoreBasic]

The link:https://kazurayam.github.io/materialstore/api/com/kazurayam/materialstore/core/Store.html[com.kazurayam.materialstore.core.Store] class create the `store` directory and the directory structure under it. The class implements methods to operate the `store` --- write a byte array into the store to make it a Material; read the byte array from a Material; list the JobNames contained, list the JobTimestamps contained, list the Materials contained. copy the Materials; delete the Materials, the JobTimestamp directory and the JobName directory. Have a quick look at the sample codes that utilize the `Store` class. Then you will understand it is a convenient helper dedicated to manage the web resources (page screenshots, HTML, JSON and XML text, etc) downloaded from the web services.

=== Create a directory tree under the store to write a Material

The following code shows how to create a "store" directory, a directory tree with JobName and JobTimestamu under the "store", and write a Material.

[source]
----
include::../src/test/java/my/sample/T08StoreBasicsTest.java[lines=1..75]
----

The `T08StoreBasicsTest` class calls the method of link:https://github.com/kazurayam/materialstore-tutorial/blob/master/src/test/java/my/sample/SharedMethods.java[my.sample.SharedMethods] class. Read its code as well.

By executing this code, the following directory tree will be created:

[source]
----
$ tree build/tmp/testOutput/my.sample.T08StoreBasicsTest/
build/tmp/testOutput/my.sample.T08StoreBasicsTest/
└── store
    └── test_write_a_Material_into_the_store
        └── 20230520_181718
            ├── index
            └── objects
                └── 27b2d39436d0655e7e8885c7f2a568a646164280.png
----

In the above tree, you can find some variable parts and fixed parts:

- *store*`/`*JobName*`/`*JobTimestamp*`/index`
- *store*`/`*JobName*`/`*JobTimestamp*`/objects/`*40 hex-decimal character*`.`*extension*

The top directory can have any name, but I usually name it `store`.

The file name `index` is fixed. The `index` file is created by the `store` object. Programmers are not supposed to operate on it directly.

The *JobName* can be any name, but there are a few characters that are not allowed as file name by OS. For example, a slash `/` is not allowed.

The *JobTimestamp* is a string of fix 15 characters: 4 digits as Year ('2023', etc), 2 digits as Month (`01`-`12`), 2 digits as Day (`01`-`31`), an under bar `_`, 2 digits as Hours (`00`- `23`), 2 digits as Minutes (`00`-`59`), 2 digits as Seconds (`00`-`59`). Exceptionally, *JobTimestamp* can be a single under bar character `_`, which means the "unspecified".

The directory name `objects` is fixed. Under the `objects`

The name of the files under the `objects` directory is a concatination of 40 hex-decimal characters derived from the content by SHA1 Message signagure algorithm appended with `.` and the *extension*.

The *extension* is something you all know: `txt`, `png`, `jpg`, `json`, `html`, `css`, `html`, `json`, `xml`, etc. The link:https://github.com/kazurayam/materialstore/blob/develop/src/main/java/com/kazurayam/materialstore/core/FileType.java[`com.kazurayam.materialstore.core.FileSystem`] defines the supported extensions. The *extesion* makes it possible to open each files by a double click action in the Windows Explorer GUI.

The *store* directory may contain multiple *JobName* directories. A *JobName* directory may contain multiple *JobTimestamp* directories. A *JobTimestamp* will contain a single `index` file. An `objects` directory may contain multiple files.

=== Read the content of a single Material as a byte[]

You can read the content of a Material as file by calling `Store.read(Material)` method.

[source]
----
include::../src/test/java/my/sample/T08StoreBasicsTest.java[lines=76..89]
----
